# Generated by Django 2.2.6 on 2020-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_centreadminprofile_stateadminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateSchemeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField(max_length=5000)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UK', 'Uttrakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LH', 'Ladakh')], default=False, max_length=25)),
                ('monetory_benefits', models.IntegerField(default=False)),
                ('eligibility_criterion', models.TextField(max_length=5000)),
                ('max_yearly_income', models.IntegerField(default=False)),
                ('religion', models.CharField(choices=[('H', 'Hindu'), ('M', 'Muslim'), ('C', 'Christian'), ('S', 'Sikh'), ('O', 'Others'), ('N', 'NIL')], default='N', max_length=1)),
                ('caste', models.CharField(choices=[('G', 'General'), ('E', 'EWS'), ('O', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='G', max_length=2)),
                ('BPL', models.BooleanField()),
                ('age', models.IntegerField(default=False)),
                ('family_members', models.IntegerField(default=False)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=1)),
                ('minority', models.BooleanField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StateAdminProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CentreSchemeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField(max_length=5000)),
                ('monetory_benefits', models.IntegerField(default=False)),
                ('eligibility_criterion', models.TextField(max_length=5000)),
                ('max_yearly_income', models.IntegerField(default=False)),
                ('religion', models.CharField(choices=[('H', 'Hindu'), ('M', 'Muslim'), ('C', 'Christian'), ('S', 'Sikh'), ('O', 'Others'), ('N', 'NIL')], default='N', max_length=1)),
                ('caste', models.CharField(choices=[('G', 'General'), ('E', 'EWS'), ('O', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='G', max_length=2)),
                ('BPL', models.BooleanField()),
                ('age', models.IntegerField(default=False)),
                ('family_members', models.IntegerField(default=False)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=1)),
                ('is_admin', models.BooleanField()),
                ('minority', models.BooleanField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CentreAdminProfile')),
            ],
        ),
    ]
