# Generated by Django 2.2.6 on 2020-07-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateschemelist',
            name='state',
        ),
    ]
